!!python/object:argparse.Namespace
batch_size: 32
clipping: 10000
dataset: cifar100
device: cuda
exp_name: cifar100_er_long
gpu: 0
lr: 0.1
model: resnet32
momentum: 0.9
nepochs: 3
num_tasks: 10
num_workers: 0
optimizer: SGD
results: ../results/cifar100
save_models: true
scenario: new_classes_incremental
schedule: true
seed: 0
strategy: er
memory_size: 2000
val_size: 0.05
weight_decay: 0.0002
lmb: 1.0
lmb2: 0.99
mean_evaluation: false
parallel_evaluation: true
eval_on_previous: true
tensorboard: true
every: 1
use_transforms: true
