!!python/object:argparse.Namespace
batch_size: 32
clipping: 10000
dataset: mini_imagenet
device: cuda
exp_name: mini_imagenet_iid
gpu: 0
lr: 0.1
model: resnet18
momentum: 0
nepochs: 3
num_tasks: 1
num_workers: 0
optimizer: SGD
results: ../results/mini_imagenet
save_models: true
scenario: new_classes_incremental
schedule: false
seed: 0
strategy: er
memory_size: 10000
val_size: 0.05
weight_decay: 0.0
lmb: 1.0
lmb2: 0.99
mean_evaluation: false
parallel_evaluation: true
eval_on_previous: true
tensorboard: true
every: 1
eval_mode: iteration
